package testhelpers;

import java.awt.AWTException;
import java.awt.Robot;
import java.awt.event.KeyEvent;
import java.io.IOException;
import skills.*;

public class YakTrackSkillRun {
	
	public static void yakAgilityRun(Robot robot, String yakTaskSelection, String yakTaskQuantity) throws IOException, 
	AWTException, InterruptedException{
		
		Agility.yakAgilityTotal(robot, yakTaskQuantity);
		
		
	}
	
	public static void yakArchaeologyRun(Robot robot, String yakTaskSelection, String yakTaskQuantity) throws IOException, 
	AWTException, InterruptedException{
		
		Archaeology.yakArchaeologyTotal(robot, yakTaskQuantity);
		
	}
	
	public static void yakConstructionRun(Robot robot, String yakTaskSelection, String yakTaskQuantity) throws IOException, 
	AWTException, InterruptedException{
		
		Construction.yakConstructionTotal(robot, yakTaskQuantity);
		
	}
	
	public static void yakCraftingRun(Robot robot, String yakTaskSelection, String yakTaskQuantity) throws IOException, 
	AWTException, InterruptedException{
		
		Crafting.yakCraftingTotal(robot, yakTaskQuantity);
		Thread.sleep(500);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Crafting Leather Gloves");
		Thread.sleep(500);
		Crafting.leatherGloves(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Crafting Leather Cowls");
		Thread.sleep(500);
		Crafting.leatherCowl(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Crafting Leather Boots");
		Thread.sleep(500);
		Crafting.leatherBoots(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Crafting Leather Chaps");
		Thread.sleep(500);
		Crafting.leatherChaps(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Crafting Leather Bodies");
		Thread.sleep(500);
		Crafting.leatherBody(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Crafting Leather Vambraces");
		Thread.sleep(500);
		Crafting.leatherVambraces(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Crafting Leather Shields");
		Thread.sleep(500);
		Crafting.leatherShield(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Crafting Hard Leather Cowls");
		Thread.sleep(500);
		Crafting.hardLeatherCowl(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Crafting Hard Leather Gloves");
		Thread.sleep(500);
		Crafting.hardLeatherGloves(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Crafting Hard Leather Boots");
		Thread.sleep(500);
		Crafting.hardLeatherBoots(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Crafting Hard Leather Bodies");
		Thread.sleep(500);
		Crafting.hardLeatherBody(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Crafting Hard Leather Chaps");
		Thread.sleep(500);
		Crafting.hardLeatherChaps(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Crafting Hard Leather Shields");
		Thread.sleep(500);
		Crafting.hardLeatherShield(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Crafting Studded Leather Coifs");
		Thread.sleep(500);
		Crafting.studdedLeatherCoif(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Crafting Studded Bodies");
		Thread.sleep(500);
		Crafting.studdedLeatherBody(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Crafting Studded Leather Gloves");
		Thread.sleep(500);
		Crafting.studdedLeatherGloves(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Crafting Studded Leather Boots");
		Thread.sleep(500);
		Crafting.studdedLeatherBoots(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Crafting Studded Leather Chaps");
		Thread.sleep(500);
		Crafting.studdedLeatherChaps(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Crafting Studded Leather Shields");
		Thread.sleep(500);
		Crafting.studdedLeatherShields(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Crafting Snakeskin Boots");
		Thread.sleep(500);
		Crafting.snakeskinBoots(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Crafting Snakeskin Vambraces");
		Thread.sleep(500);
		Crafting.snakeskinVambraces(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Crafting Snakeskin Bandanas");
		Thread.sleep(500);
		Crafting.snakeskinBandana(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Crafting Snakeskin Chaps");
		Thread.sleep(500);
		Crafting.snakeskinChaps(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Crafting Snakeskin Bodies");
		Thread.sleep(500);
		Crafting.snakeskinBody(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Crafting Green Dragonhide Vambraces");
		Thread.sleep(500);
		Crafting.greenDragonhideVambraces(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Crafting Green Dragonhide Boots");
		Thread.sleep(500);
		Crafting.greenDragonhideBoots(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Crafting Green Dragonhide Chaps");
		Thread.sleep(500);
		Crafting.greenDragonhideChaps(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Crafting Green Dragonhide Coifs");
		Thread.sleep(500);
		Crafting.greenDragonhideCoif(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Crafting Green Dragonhide Bodies");
		Thread.sleep(500);
		Crafting.greenDragonhideBody(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Crafting Green Dragonhide Shields");
		Thread.sleep(500);
		Crafting.greenDragonhideShield(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Crafting Blue Dragonhide Vambraces");
		Thread.sleep(500);
		Crafting.blueDragonhideVambraces(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Crafting Blue Dragonhide Boots");
		Thread.sleep(500);
		Crafting.blueDragonhideBoots(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Crafting Blue Dragonhide Chaps");
		Thread.sleep(500);
		Crafting.blueDragonhideChaps(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Crafting Blue Dragonhide Coifs");
		Thread.sleep(500);
		Crafting.blueDragonhideCoif(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Crafting Blue Dragonhide Bodies");
		Thread.sleep(500);
		Crafting.blueDragonhideBody(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Crafting Blue Dragonhide Shields");
		Thread.sleep(500);
		Crafting.blueDragonhideShield(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Crafting Red Dragonhide Vambraces");
		Thread.sleep(500);
		Crafting.redDragonhideVambraces(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Crafting Red Dragonhide Boots");
		Thread.sleep(500);
		Crafting.redDragonhideBoots(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Crafting Red Dragonhide Chaps");
		Thread.sleep(500);
		Crafting.redDragonhideChaps(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Crafting Red Dragonhide Coifs");
		Thread.sleep(500);
		Crafting.redDragonhideCoif(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Crafting Red Dragonhide Bodies");
		Thread.sleep(500);
		Crafting.redDragonhideBody(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Crafting Red Dragonhide Shields");
		Thread.sleep(500);
		Crafting.redDragonhideShield(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Crafting Black Dragonhide Vambraces");
		Thread.sleep(500);
		Crafting.blackDragonhideVambraces(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Crafting Black Dragonhide Boots");
		Thread.sleep(500);
		Crafting.blackDragonhideBoots(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Crafting Black Dragonhide Chaps");
		Thread.sleep(500);
		Crafting.blackDragonhideChaps(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Crafting Black Dragonhide Coifs");
		Thread.sleep(500);
		Crafting.blackDragonhideCoif(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Crafting Black Dragonhide Bodies");
		Thread.sleep(500);
		Crafting.blackDragonhideBody(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Crafting Black Dragonhide Shields");
		Thread.sleep(500);
		Crafting.blackDragonhideShield(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Crafting Royal Dragonhide Vambraces");
		Thread.sleep(500);
		Crafting.royalDragonhideVambraces(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Crafting Royal Dragonhide Boots");
		Thread.sleep(500);
		Crafting.royalDragonhideBoots(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Crafting Royal Dragonhide Chaps");
		Thread.sleep(500);
		Crafting.royalDragonhideChaps(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Crafting Royal Dragonhide Coifs");
		Thread.sleep(500);
		Crafting.royalDragonhideCoif(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Crafting Royal Dragonhide Bodies");
		Thread.sleep(500);
		Crafting.royalDragonhideBody(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
	
	}
	
	public static void yakCookingRun(Robot robot, String yakTaskSelection, String yakTaskQuantity) throws IOException, 
	AWTException, InterruptedException{
		
		Cooking.yakCookingTotal(robot, yakTaskQuantity);
		Thread.sleep(1000);
		Cooking.cookingQuests(robot);
		Thread.sleep(1000);
		Cooking.burthorpOven(robot);
		Thread.sleep(2000);
		//Meat
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Cooking Cooked Chicken");
		Thread.sleep(500);
		Cooking.cookedChicken(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Cooking Cooked Meat");
		Thread.sleep(500);
		Cooking.cookedMeat(robot, yakTaskSelection);
		Thread.sleep(5000);
		//Fish
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Cooking Crayfish");
		Thread.sleep(500);
		Cooking.crayfish(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Cooking Shrimp");
		Thread.sleep(500);
		Cooking.shrimp(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Cooking Herring");
		Thread.sleep(500);
		Cooking.herring(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Cooking Mackerel");
		Thread.sleep(500);
		Cooking.mackerel(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Cooking Trout");
		Thread.sleep(500);
		Cooking.trout(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Cooking Cod");
		Thread.sleep(500);
		Cooking.cod(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Cooking Pike");
		Thread.sleep(500);
		Cooking.pike(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Cooking Salmon");
		Thread.sleep(500);
		Cooking.salmon(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Cooking Tuna");
		Thread.sleep(500);
		Cooking.tuna(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Cooking Rainbow Fish");
		Thread.sleep(500);
		Cooking.huntingFishSpecial(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Cooking Lobster");
		Thread.sleep(500);
		Cooking.lobster(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Cooking Bass");
		Thread.sleep(500);
		Cooking.bass(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Cooking Swordfish");
		Thread.sleep(500);
		Cooking.swordfish(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Cooking Desert Sole");
		Thread.sleep(500);
		Cooking.menaphosFishLow(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Cooking Catfish");
		Thread.sleep(500);
		Cooking.menaphosFishMedium(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Cooking Monkfish");
		Thread.sleep(500);
		Cooking.monkfish(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Cooking Beltfish");
		Thread.sleep(500);
		Cooking.menaphosFishHigh(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Cooking Jellyfish Green");
		Thread.sleep(500);
		Cooking.jellyFishLow(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Cooking Shark");
		Thread.sleep(500);
		Cooking.shark(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Cooking Cavefish");
		Thread.sleep(500);
		Cooking.cavefish(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Cooking Fish Oil");
		Thread.sleep(500);
		Cooking.fishOil(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Cooking Mantaray");
		Thread.sleep(500);
		Cooking.mantaray(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Cooking Rocktail");
		Thread.sleep(500);
		Cooking.rocktail(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Cooking Jellyfish Blue");
		Thread.sleep(500);
		Cooking.jellyfishHigh(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Cooking Sailfish");
		Thread.sleep(500);
		Cooking.sailfish(robot, yakTaskSelection);
		Thread.sleep(5000);
		//Bread
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Cooking Plain Pizza");
		Thread.sleep(500);
		Cooking.plainPizza(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Cooking Pitta Bread");
		Thread.sleep(500);
		Cooking.pittaBread(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		//Pies
		DebugProcs.setYakRecipe(robot, "Cooking Redberry Pie");
		Thread.sleep(500);
		Cooking.redberryPie(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Cooking Meat Pie");
		Thread.sleep(500);
		Cooking.meatPie(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Cooking Apple Pie");
		Thread.sleep(500);
		Cooking.applePie(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		//Cakes
		DebugProcs.setYakRecipe(robot, "Cooking Cake");
		Thread.sleep(500);
		Cooking.cake(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		//Baked Potatoes
		DebugProcs.setYakRecipe(robot, "Cooking Baked Potato");
		Thread.sleep(500);
		Cooking.potatoBaked(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		//Churning 
		DebugProcs.clearInv(robot);
		Thread.sleep(1000);
		Cooking.sinclairChurn(robot);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Cooking Pot of Cream");
		Thread.sleep(500);
		Cooking.potOfCream(robot, yakTaskSelection);
		Thread.sleep(8000);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Cooking Pat of Butter");
		Thread.sleep(500);
		Cooking.potOfButter(robot, yakTaskSelection);
		Thread.sleep(8000);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Cooking Cheese Wheel");
		Thread.sleep(500);
		Cooking.cheeseWheel(robot, yakTaskSelection);
		Thread.sleep(8000);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Cooking Cheese Wheel Butter Churning");
		Thread.sleep(500);
		Cooking.cheeseWheelBC(robot, yakTaskSelection);
		Thread.sleep(8000);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Cooking Pat of Butter Cream Churning");
		Thread.sleep(500);
		Cooking.patofButterCC(robot, yakTaskSelection);
		Thread.sleep(8000);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Cooking Cheese Wheel Cream Churning");
		Thread.sleep(500);
		Cooking.cheeseWheelCC(robot, yakTaskSelection);
		Thread.sleep(8000);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		
	}
	
	public static void yakDivinationRun(Robot robot, String yakTaskSelection, String yakTaskQuantity) throws IOException, 
	AWTException, InterruptedException{
		
		Divination.yakDivinationTotal(robot, yakTaskQuantity);
		Thread.sleep(3000);
		Divination.divinationQuest(robot);
		Thread.sleep(3000);
		DebugProcs.setYakRecipe(robot, "Divination pale Energy");
		Thread.sleep(500);
		Divination.paleEnergy(robot, yakTaskSelection);
		Thread.sleep(3000);
		DebugProcs.setYakRecipe(robot, "Divination Flickering Energy");
		Thread.sleep(500);
		Divination.flickeringEnergy(robot, yakTaskSelection);
		Thread.sleep(3000);
		DebugProcs.setYakRecipe(robot, "Divination Bright Energy");
		Thread.sleep(500);
		Divination.brightEnergy(robot, yakTaskSelection);
		Thread.sleep(3000);
		DebugProcs.setYakRecipe(robot, "Divination Glowing Energy");
		Thread.sleep(500);
		Divination.glowingEnergy(robot, yakTaskSelection);
		Thread.sleep(3000);
		DebugProcs.setYakRecipe(robot, "Divination Sparking Energy");
		Thread.sleep(500);
		Divination.sparkingEnergy(robot, yakTaskSelection);
		Thread.sleep(3000);
		DebugProcs.setYakRecipe(robot, "Divination Gleaming Energy");
		Thread.sleep(500);
		Divination.gleamingEnergy(robot, yakTaskSelection);
		Thread.sleep(3000);
		DebugProcs.setYakRecipe(robot, "Divination Vibrant Energy");
		Thread.sleep(500);
		Divination.vibrantEnergy(robot, yakTaskSelection);
		Thread.sleep(3000);
		DebugProcs.setYakRecipe(robot, "Divination Lustrous Energy");
		Thread.sleep(500);
		Divination.lustrousEnergy(robot, yakTaskSelection);
		Thread.sleep(3000);
		DebugProcs.setYakRecipe(robot, "Divination Elder Energy");
		Thread.sleep(500);
		Divination.elderEnergy(robot, yakTaskSelection);
		Thread.sleep(3000);
		DebugProcs.setYakRecipe(robot, "Divination Brilliant Energy");
		Thread.sleep(500);
		Divination.brilliantEnergy(robot, yakTaskSelection);
		Thread.sleep(3000);
		DebugProcs.setYakRecipe(robot, "Divination Radiant Energy");
		Thread.sleep(500);
		Divination.radiantEnergy(robot, yakTaskSelection);
		Thread.sleep(3000);
		DebugProcs.setYakRecipe(robot, "Divination Luminous Energy");
		Thread.sleep(500);
		Divination.luminousEnergy(robot, yakTaskSelection);
		Thread.sleep(3000);
		DebugProcs.setYakRecipe(robot, "Divination Positive Energy");
		Thread.sleep(500);
		Divination.positiveEnergy(robot, yakTaskSelection);
		Thread.sleep(3000);
		DebugProcs.setYakRecipe(robot, "Divination Negative Energy");
		Thread.sleep(500);
		Divination.negativeEnergy(robot, yakTaskSelection);
		Thread.sleep(3000);
		DebugProcs.setYakRecipe(robot, "Divination Incandescent Energy");
		Thread.sleep(500);
		Divination.incandescentEnergy(robot, yakTaskSelection);
		Thread.sleep(3000);
		DebugProcs.setYakRecipe(robot, "Divination Ancestral Energy");
		Thread.sleep(500);
		Divination.ancestralEnergy(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		
		
	}
	
	public static void yakDungeoneeringRun(Robot robot, String yakTaskSelection, String yakTaskQuantity) throws IOException, 
	AWTException, InterruptedException{
		
		Dungeoneering.yakDungeoneeringTotal(robot, yakTaskQuantity);
		
		
	}
	
	public static void yakFarmingRun(Robot robot, String yakTaskSelection, String yakTaskQuantity) throws IOException, 
	AWTException, InterruptedException{
		
		Farming.yakFarmingTotal(robot, yakTaskQuantity);
		
		
	}
	
	public static void yakFiremakingRun(Robot robot, String yakTaskSelection, String yakTaskQuantity) throws IOException, 
	AWTException, InterruptedException{
		
		Firemaking.yakFiremakingTotal(robot, yakTaskQuantity);
		Thread.sleep(1000);
		Firemaking.startBonfire(robot);
		Thread.sleep(8000);
		DebugProcs.setYakRecipe(robot, "Firemaking Logs");
		Thread.sleep(500);
		Firemaking.logsFire(robot, yakTaskSelection);
		Thread.sleep(12000);
		DebugProcs.setYakRecipe(robot, "Firemaking Oak");
		Thread.sleep(500);
		Firemaking.oakLogFire(robot, yakTaskSelection);
		Thread.sleep(12000);
		DebugProcs.setYakRecipe(robot, "Firemaking Willow");
		Thread.sleep(500);
		Firemaking.willowLogFire(robot, yakTaskSelection);
		Thread.sleep(12000);
		DebugProcs.setYakRecipe(robot, "Firemaking Teak");
		Thread.sleep(500);
		Firemaking.teakLogFire(robot, yakTaskSelection);
		Thread.sleep(12000);
		Firemaking.newBonfire(robot);
		Thread.sleep(8000);
		DebugProcs.setYakRecipe(robot, "Firemaking Artic Pine");
		Thread.sleep(500);
		Firemaking.articPineLogFire(robot, yakTaskSelection);
		Thread.sleep(12000);
		DebugProcs.setYakRecipe(robot, "Firemaking Maple");
		Thread.sleep(500);
		Firemaking.mapleLogFire(robot, yakTaskSelection);
		Thread.sleep(12000);
		DebugProcs.setYakRecipe(robot, "Firemaking Acadia");
		Thread.sleep(500);
		Firemaking.menaphosAcadiaLogFire(robot, yakTaskSelection);
		Thread.sleep(12000);
		DebugProcs.setYakRecipe(robot, "Firemaking Mahogany");
		Thread.sleep(500);
		Firemaking.mahoganyLogFire(robot, yakTaskSelection);
		Thread.sleep(12000);
		Firemaking.newBonfire(robot);
		Thread.sleep(8000);
		DebugProcs.setYakRecipe(robot, "Firemaking Eucalyptus");
		Thread.sleep(500);
		Firemaking.eucalyptusLogFire(robot, yakTaskSelection);
		Thread.sleep(12000);
		DebugProcs.setYakRecipe(robot, "Firemaking Yew");
		Thread.sleep(500);
		Firemaking.yewLogFire(robot, yakTaskSelection);
		Thread.sleep(12000);
		DebugProcs.setYakRecipe(robot, "Firemaking Magic Logs");
		Thread.sleep(500);
		Firemaking.magicLogFire(robot, yakTaskSelection);
		Thread.sleep(12000);
		Firemaking.newBonfire(robot);
		Thread.sleep(8000);
		DebugProcs.setYakRecipe(robot, "Firemaking Elder Logs");
		Thread.sleep(500);
		Firemaking.elderLogFire(robot, yakTaskSelection);
		Thread.sleep(12000);
		DebugProcs.setYakRecipe(robot, "Firemaking Driftwood");
		Thread.sleep(500);
		Firemaking.driftwoodLogFire(robot, yakTaskSelection);
		Thread.sleep(12000);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		
	}
	
	public static void yakFishingRun(Robot robot, String yakTaskSelection, String yakTaskQuantity) throws IOException, 
	AWTException, InterruptedException{
		
		Fishing.yakFishingTotal(robot, yakTaskQuantity);
		
				
	}
	
	public static void yakFletchingRun(Robot robot, String yakTaskSelection, String yakTaskQuantity) throws IOException, 
	AWTException, InterruptedException{
		
		Fletching.yakFletchingTotal(robot, yakTaskQuantity);
		Thread.sleep(1000);
		DebugProcs.setYakRecipe(robot, "Fletching Shortbow");
		Thread.sleep(500);
		Fletching.shortbow(robot, yakTaskSelection);
		Thread.sleep(1000);
		DebugProcs.setYakRecipe(robot, "Fletching Longbow");
		Thread.sleep(500);
		Fletching.longbow(robot, yakTaskSelection);
		Thread.sleep(1000);
		DebugProcs.setYakRecipe(robot, "Fletching Oak Shortbow");
		Thread.sleep(500);
		Fletching.oakShortbow(robot, yakTaskSelection);
		Thread.sleep(1000);
		DebugProcs.setYakRecipe(robot, "Fletching Oak Longbow");
		Thread.sleep(500);
		Fletching.oakLongBow(robot, yakTaskSelection);
		Thread.sleep(1000);
		DebugProcs.setYakRecipe(robot, "Fletching Willow Shortbow");
		Thread.sleep(500);
		Fletching.willowShortow(robot, yakTaskSelection);
		Thread.sleep(1000);
		DebugProcs.setYakRecipe(robot, "Fletching Willow Longbow");
		Thread.sleep(500);
		Fletching.willowLongbow(robot, yakTaskSelection);
		Thread.sleep(1000);
		DebugProcs.setYakRecipe(robot, "Fletching Maple Shortbow");
		Thread.sleep(500);
		Fletching.mapleShortbow(robot, yakTaskSelection);
		Thread.sleep(1000);
		DebugProcs.setYakRecipe(robot, "Fletching Maple Longbow");
		Thread.sleep(500);
		Fletching.mapleLongbow(robot, yakTaskSelection);
		Thread.sleep(1000);
		DebugProcs.setYakRecipe(robot, "Fletching Yew Shortbow");
		Thread.sleep(500);
		Fletching.yewShortbow(robot, yakTaskSelection);
		Thread.sleep(1000);
		DebugProcs.setYakRecipe(robot, "Fletching Yew Longbow");
		Thread.sleep(500);
		Fletching.yewLongbow(robot, yakTaskSelection);
		Thread.sleep(1000);
		DebugProcs.setYakRecipe(robot, "Fletching Magic Shortbow");
		Thread.sleep(500);
		Fletching.magicShortbow(robot, yakTaskSelection);
		Thread.sleep(1000);
		DebugProcs.setYakRecipe(robot, "Fletching Magic Longbow");
		Thread.sleep(500);
		Fletching.magicLongbow(robot, yakTaskSelection);
		Thread.sleep(1000);
		DebugProcs.setYakRecipe(robot, "Fletching Elder Shortbow");
		Thread.sleep(500);
		Fletching.elderShortbow(robot, yakTaskSelection);
		Thread.sleep(1000);
		DebugProcs.setYakRecipe(robot, "Fletching Elder Longbow");
		Thread.sleep(500);
		Fletching.elderLongbow(robot, yakTaskSelection);
		Thread.sleep(1000);
		DebugProcs.setYakRecipe(robot, "Fletching Bronze Crossbow");
		Thread.sleep(500);
		Fletching.bronzeXbow(robot, yakTaskSelection);
		Thread.sleep(1000);
		DebugProcs.setYakRecipe(robot, "Fletching Bronze Crossbow Offhand");
		Thread.sleep(500);
		Fletching.bronzeXbowO(robot, yakTaskSelection);
		Thread.sleep(1000);
		DebugProcs.setYakRecipe(robot, "Fletching Bronze 2H Crossbow");
		Thread.sleep(500);
		Fletching.bronze2HXbow(robot, yakTaskSelection);
		Thread.sleep(1000);
		DebugProcs.setYakRecipe(robot, "Fletching Blurite Crossbow");
		Thread.sleep(500);
		Fletching.bluriteXbow(robot, yakTaskSelection);
		Thread.sleep(1000);
		DebugProcs.setYakRecipe(robot, "Fletching Blurite Crossbow Offhand");
		Thread.sleep(500);
		Fletching.bluriteXbowO(robot, yakTaskSelection);
		Thread.sleep(1000);
		DebugProcs.setYakRecipe(robot, "Fletching Blurite 2H Crossbow");
		Thread.sleep(500);
		Fletching.blurite2HXbow(robot, yakTaskSelection);
		Thread.sleep(1000);
		DebugProcs.setYakRecipe(robot, "Fletching Iron Crossbow");
		Thread.sleep(500);
		Fletching.ironXbow(robot, yakTaskSelection);
		Thread.sleep(1000);
		DebugProcs.setYakRecipe(robot, "Fletching Iron Crossbow Offhand");
		Thread.sleep(500);
		Fletching.ironXbowO(robot, yakTaskSelection);
		Thread.sleep(1000);
		DebugProcs.setYakRecipe(robot, "Fletching Iron 2H Crossbow");
		Thread.sleep(500);
		Fletching.iron2HXbow(robot, yakTaskSelection);
		Thread.sleep(1000);
		DebugProcs.setYakRecipe(robot, "Fletching Steel Crossbow");
		Thread.sleep(500);
		Fletching.steelXbow(robot, yakTaskSelection);
		Thread.sleep(1000);
		DebugProcs.setYakRecipe(robot, "Fletching Steel Crossbow Offhand");
		Thread.sleep(500);
		Fletching.steelXbowO(robot, yakTaskSelection);
		Thread.sleep(1000);
		DebugProcs.setYakRecipe(robot, "Fletching Steel 2H Crossbow");
		Thread.sleep(500);
		Fletching.steel2HXbow(robot, yakTaskSelection);
		Thread.sleep(1000);
		DebugProcs.setYakRecipe(robot, "Fletching Mithril Crossbow");
		Thread.sleep(500);
		Fletching.mithrilXbow(robot, yakTaskSelection);
		Thread.sleep(1000);
		DebugProcs.setYakRecipe(robot, "Fletching Mithril Crossbow Offhand");
		Thread.sleep(500);
		Fletching.mithrilXbowO(robot, yakTaskSelection);
		Thread.sleep(1000);
		DebugProcs.setYakRecipe(robot, "Fletching Mithril 2H Crossbow");
		Thread.sleep(500);
		Fletching.mithril2HXbow(robot, yakTaskSelection);
		Thread.sleep(1000);
		DebugProcs.setYakRecipe(robot, "Fletching Adamant Crossbow");
		Thread.sleep(500);
		Fletching.adamantXbow(robot, yakTaskSelection);
		Thread.sleep(1000);
		DebugProcs.setYakRecipe(robot, "Fletching Adamant Crossbow Offhand");
		Thread.sleep(500);
		Fletching.adamantXbowO(robot, yakTaskSelection);
		Thread.sleep(1000);
		DebugProcs.setYakRecipe(robot, "Fletching Adamant 2H Crossbow");
		Thread.sleep(500);
		Fletching.adamant2HXbow(robot, yakTaskSelection);
		Thread.sleep(1000);
		DebugProcs.setYakRecipe(robot, "Fletching Runite Crossbow");
		Thread.sleep(500);
		Fletching.runiteXbow(robot, yakTaskSelection);
		Thread.sleep(1000);
		DebugProcs.setYakRecipe(robot, "Fletching Runite Crossbow Offhand");
		Thread.sleep(500);
		Fletching.runiteXbowO(robot, yakTaskSelection);
		Thread.sleep(1000);
		DebugProcs.setYakRecipe(robot, "Yak Task = Fletching Runite 2H Crossbow");
		Thread.sleep(500);
		Fletching.runite2HXbow(robot, yakTaskSelection);
		Thread.sleep(1000);
		DebugProcs.setYakRecipe(robot, "Fletching Dragon Crossbow");
		Thread.sleep(500);
		Fletching.dragonXbow(robot, yakTaskSelection);
		Thread.sleep(1000);
		DebugProcs.setYakRecipe(robot, "Fletching Dragon Crossbow Offhand");
		Thread.sleep(500);
		Fletching.dragonXbowO(robot, yakTaskSelection);
		Thread.sleep(1000);
		DebugProcs.setYakRecipe(robot, "Fletching Dragon 2H Crossbow");
		Thread.sleep(500);
		Fletching.dragon2HXbow(robot, yakTaskSelection);
		Thread.sleep(1000);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		
	}
	
	public static void yakHerbloreRun(Robot robot, String yakTaskSelection, String yakTaskQuantity) throws IOException, 
	AWTException, InterruptedException{
		
		Herblore.yakHerbloreTotal(robot, yakTaskQuantity);
		Thread.sleep(1000);
		DebugProcs.setYakRecipe(robot, "Herblore Attack Potion");
		Thread.sleep(500);
		Herblore.attackPotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Ranging Potion");
		Thread.sleep(500);
		Herblore.rangingPotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Magic Potion");
		Thread.sleep(500);
		Herblore.magicPotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Strength Potion");
		Thread.sleep(500);
		Herblore.strengthPotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Defence Potion");
		Thread.sleep(500);
		Herblore.defencePotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Antipoison");
		Thread.sleep(500);
		Herblore.antiPoison(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Restore Potion");
		Thread.sleep(500);
		Herblore.restorePotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Energy Potion");
		Thread.sleep(500);
		Herblore.energyPotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Agility Potion");
		Thread.sleep(500);
		Herblore.agilityPotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Combat Potion");
		Thread.sleep(500);
		Herblore.combatPotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Prayer Potion");
		Thread.sleep(500);
		Herblore.prayerPotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Summoning Potion");
		Thread.sleep(500);
		Herblore.summoningPotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Crafting Potion");
		Thread.sleep(500);
		Herblore.craftingPotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Divination Potion");
		Thread.sleep(500);
		Herblore.divinationPotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Super Attack Potion");
		Thread.sleep(500);
		Herblore.superAttackPotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Super Antipoison");
		Thread.sleep(500);
		Herblore.superAntipoisonPotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Fishing Potion");
		Thread.sleep(500);
		Herblore.fishingPotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Super Energy Potion");
		Thread.sleep(500);
		Herblore.superEnergyPotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Hunter Potion");
		Thread.sleep(500);
		Herblore.hunterPotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Runecrafting Potion");
		Thread.sleep(500);
		Herblore.runecraftingPotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Super Strength Potion");
		Thread.sleep(500);
		Herblore.cookingPotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Cooking Potion");
		Thread.sleep(500);
		Herblore.superStrengthPotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Luck Potion");
		Thread.sleep(500);
		Herblore.luckPotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Fletching Potion");
		Thread.sleep(500);
		Herblore.fletchingPotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Weapon Poison");
		Thread.sleep(500);
		Herblore.weaponPoison(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Super Restore Potion");
		Thread.sleep(500);
		Herblore.superRestorePotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Super Prayer Potion");
		Thread.sleep(500);
		Herblore.superPrayerPotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Super Hunter Potion");
		Thread.sleep(500);
		Herblore.superHunterPotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Camouflage Potion");
		Thread.sleep(500);
		Herblore.camouflagePotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Super Defence Potion");
		Thread.sleep(500);
		Herblore.superdefencePotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Antipoison+");
		Thread.sleep(500);
		Herblore.antiPoisonPlus(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Antifire");
		Thread.sleep(500);
		Herblore.antifire(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Super Divination Potion");
		Thread.sleep(500);
		Herblore.superDivinationPotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Super Ranging Potion");
		Thread.sleep(500);
		Herblore.superRangingPotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Weapon Poison+");
		Thread.sleep(500);
		Herblore.weaponPoisonPlus(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Super Runecrafting Potion");
		Thread.sleep(500);
		Herblore.superRunecraftingPotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Super Magic Potion");
		Thread.sleep(500);
		Herblore.superMagicPotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Invention Potion");
		Thread.sleep(500);
		Herblore.inventionPotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Stamina Potion");
		Thread.sleep(500);
		Herblore.staminaPotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Zamorak Brew");
		Thread.sleep(500);
		Herblore.zamorakBrew(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Super Cooking Potion");
		Thread.sleep(500);
		Herblore.superCookingPotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Antipoison++");
		Thread.sleep(500);
		Herblore.antiPoisonPlusPlus(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Antidote++");
		Thread.sleep(500);
		Herblore.antidotePlusPlus(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Extreme Hunter Potion");
		Thread.sleep(500);
		Herblore.extremeHunterPotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Saradomin Brew");
		Thread.sleep(500);
		Herblore.saradominBrew(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Weapon Poison++");
		Thread.sleep(500);
		Herblore.weaponPoisonPlusPlus(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Aggression Potion");
		Thread.sleep(500);
		Herblore.aggressionPotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Adrenaline Potion");
		Thread.sleep(500);
		Herblore.adrenalinePotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Super Adrenaline Potion");
		Thread.sleep(500);
		Herblore.superAdrenalinePotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Super Antifire");
		Thread.sleep(500);
		Herblore.superAntifire(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Super Invention Potion");
		Thread.sleep(500);
		Herblore.superInventionPotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Extreme Attack Potion");
		Thread.sleep(500);
		Herblore.extremeAttackPotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Extreme Strength Potion");
		Thread.sleep(500);
		Herblore.extremeStrengthPotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Extreme Divination Potion");
		Thread.sleep(500);
		Herblore.extremeDivinationPotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Extreme Defence Potion");
		Thread.sleep(500);
		Herblore.extremeDefencePotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Extended Super Antifire Potion");
		Thread.sleep(500);
		Herblore.extendedSuperAntifirePotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Extreme Super Antifire Potion");
		Thread.sleep(500);
		Herblore.extremeSuperAntifirePotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Extreme Magic Potion");
		Thread.sleep(500);
		Herblore.extremeMagicPotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Extreme Runecrafting Potion");
		Thread.sleep(500);
		Herblore.extremeRunecraftingPotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Extreme Ranging Potion");
		Thread.sleep(500);
		Herblore.extremeRangingPotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Super Saradomin Brew");
		Thread.sleep(500);
		Herblore.superSaradominBrew(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Super Zamorak Brew");
		Thread.sleep(500);
		Herblore.superZamorakBrew(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Prayer Renewal Potion");
		Thread.sleep(500);
		Herblore.prayerRenewalPotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Extreme Invention Potion");
		Thread.sleep(500);
		Herblore.extremeInventionPotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Harvest Potion");
		Thread.sleep(500);
		Herblore.harvestPotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Overload Potion");
		Thread.sleep(500);
		Herblore.overloadPotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Weapon Poison+++");
		Thread.sleep(500);
		Herblore.weaponPoisonPlusPlusPlus(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Charming Potion");
		Thread.sleep(500);
		Herblore.charmingPotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Extreme Cooking Potion");
		Thread.sleep(500);
		Herblore.extremeCookingPotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Extreme Prayer Potion");
		Thread.sleep(500);
		Herblore.extremePrayerPotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Powerburst Of Vitality");
		Thread.sleep(500);
		Herblore.powerburstOfVitality(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Powerburst Of Masterstroke");
		Thread.sleep(500);
		Herblore.powerburstOfMasterstroke(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Powerburst Of Sorcery");
		Thread.sleep(500);
		Herblore.powerburstOfSorcery(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Powerburst Of Acceleration");
		Thread.sleep(500);
		Herblore.powerburstOfAcceleration(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Powerburst Of Feats");
		Thread.sleep(500);
		Herblore.powerburstOfFeats(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Yak Task = Herblore Powerburst Of Overkill");
		Thread.sleep(500);
		Herblore.powerburstOfOverkill(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Elder Overload Potion");
		Thread.sleep(500);
		Herblore.elderOverloadPotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Elder Overload Salve");
		Thread.sleep(500);
		Herblore.elderOverloadSalve(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Herblore Spiritual Prayer Potion");
		Thread.sleep(500);
		Herblore.spiritualPrayerPotion(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		
	}
	
	public static void yakMiningRun(Robot robot, String yakTaskSelection, String yakTaskQuantity) throws IOException, 
	AWTException, InterruptedException{
		
		DebugProcs.setNPCAttack(robot);
		Thread.sleep(5000);
		Mining.yakMiningTotal(robot, yakTaskQuantity);
		Thread.sleep(1000);
		DebugProcs.setYakRecipe(robot, "Mining Copper");
		Thread.sleep(500);
		Mining.copperOre(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Mining Tin");
		Thread.sleep(500);
		Mining.tinOre(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Mining Iron");
		Thread.sleep(500);
		Mining.ironOre(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Mining Coal");
		Thread.sleep(500);
		Mining.coalOre(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Mining Mithril");
		Thread.sleep(500);
		Mining.mithrilOre(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Mining Adamantite");
		Thread.sleep(500);
		Mining.adamantiteOre(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Mining Luminite");
		Thread.sleep(500);
		Mining.luminiteOre(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Mining Runite");
		Thread.sleep(500);
		Mining.runiteOre(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Mining Orichalcite");
		Thread.sleep(500);
		Mining.orichalcite(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Mining Drakolith");
		Thread.sleep(500);
		Mining.drakolithOre(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Mining Necrite");
		Thread.sleep(500);
		Mining.necriteOre(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Mining Phasmatite");
		Thread.sleep(500);
		Mining.phasmatiteOre(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Mining Banite");
		Thread.sleep(500);
		Mining.baniteOre(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Mining Light Animica");
		Thread.sleep(500);
		Mining.lightAnimica(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Mining Dark Animica");
		Thread.sleep(500);
		Mining.darkAnimica(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		
	}
	
	public static void yakPrayerRun(Robot robot, String yakTaskSelection, String yakTaskQuantity) throws IOException, 
	AWTException, InterruptedException{
		
		Prayer.yakPrayerTotal(robot, yakTaskQuantity);
		Thread.sleep(1000);
		DebugProcs.setYakRecipe(robot, "Prayer Impious Ashes");
		Thread.sleep(500);
		Prayer.impiousAshes(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Prayer Impious Ashes (Rand)");
		Thread.sleep(500);
		Prayer.randImpiousAshes(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Prayer Bones");
		Thread.sleep(500);
		Prayer.bones(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Prayer Wolf Bones");
		Thread.sleep(500);
		Prayer.wolfBones(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Prayer Monkey Bones");
		Thread.sleep(500);
		Prayer.monkeyBones(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Prayer Bat Bones");
		Thread.sleep(500);
		Prayer.batBones(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Prayer Accursed Ashes");
		Thread.sleep(500);
		Prayer.accursedAshes(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Prayer Accursed Ashes (Rand)");
		Thread.sleep(500);
		Prayer.randAccursedAshes(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Prayer Jogre Bones");
		Thread.sleep(500);
		Prayer.jorgeBones(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Prayer Big Bones");
		Thread.sleep(500);
		Prayer.bigBones(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Prayer Zogre Bones");
		Thread.sleep(500);
		Prayer.zorgeBones(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Prayer Baby Dragon Bones");
		Thread.sleep(500);
		Prayer.babyDragonBones(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Prayer Wyvern Bones");
		Thread.sleep(500);
		Prayer.wyvernBones(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Prayer Infernal Ashes");
		Thread.sleep(500);
		Prayer.infernalAshes(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Prayer Infernal Ashes (Rand)");
		Thread.sleep(500);
		Prayer.randInfernalAshes(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Prayer Dragon Bones");
		Thread.sleep(500);
		Prayer.dragonBones(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Prayer Creature Bones");
		Thread.sleep(500);
		Prayer.creatureBones(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Prayer Dagannoth Bones");
		Thread.sleep(500);
		Prayer.dagannothBones(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Prayer Adamant Dragon Bones");
		Thread.sleep(500);
		Prayer.adamantDragonBones(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Prayer Frost Dragon Bones");
		Thread.sleep(500);
		Prayer.frostDragonBones(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Prayer Rune Dragon Bones");
		Thread.sleep(500);
		Prayer.runeDragonBones(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Prayer Smoldering Ashes");
		Thread.sleep(500);
		Prayer.smoulderingAshes(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection); 
		
	}
	
	public static void yakRunecraftingRun(Robot robot, String yakTaskSelection, String yakTaskQuantity) throws IOException, 
	AWTException, InterruptedException{
		
		Runecrafting.yakRunecraftingTotal(robot, yakTaskQuantity);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Runecrafting Air Rune");
		Thread.sleep(500);
		Runecrafting.airRune(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Runecrafting Mind Rune");
		Thread.sleep(500);
		Runecrafting.mindRune(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Runecrafting Water Rune");
		Thread.sleep(500);
		Runecrafting.waterRune(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Runecrafting Earth Rune");
		Thread.sleep(500);
		Runecrafting.earthRune(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Runecrafting Fire Rune");
		Thread.sleep(500);
		Runecrafting.fireRune(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Runecrafting Body Rune");
		Thread.sleep(500);
		Runecrafting.bodyRune(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Runecrafting Cosmic Rune");
		Thread.sleep(500);
		Runecrafting.cosmicRune(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Runecrafting Chaos Rune");
		Thread.sleep(500);
		Runecrafting.chaosRune(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Runecrafting Astral Rune");
		Thread.sleep(500);
		Runecrafting.astralRune(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Runecrafting Nature Rune");
		Thread.sleep(500);
		Runecrafting.natureRune(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Runecrafting Law Rune");
		Thread.sleep(500);
		Runecrafting.lawRune(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Runecrafting Death Rune");
		Thread.sleep(500);
		Runecrafting.deathRune(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Runecrafting Blood Rune");
		Thread.sleep(500);
		Runecrafting.bloodRune(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Runecrafting Soul Rune");
		Thread.sleep(500);
		Runecrafting.soulRune(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Runecrafting Siphon Air Rune");
		Thread.sleep(500);
		Runecrafting.airRuneSiphon(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Runecrafting Siphon Mind Rune");
		Thread.sleep(500);
		Runecrafting.mindRuneSiphon(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Runecrafting Siphon Water Rune");
		Thread.sleep(500);
		Runecrafting.waterRuneSiphon(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Runecrafting Siphon Earth Rune");
		Thread.sleep(500);
		Runecrafting.earthRuneSiphon(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Runecrafting Siphon Fire Rune");
		Thread.sleep(500);
		Runecrafting.fireRuneSiphon(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Runecrafting Siphon Body Rune");
		Thread.sleep(500);
		Runecrafting.bodyRuneSiphon(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Runecrafting Siphon Cosmic Rune");
		Thread.sleep(500);
		Runecrafting.cosmicRuneSiphon(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Runecrafting Siphon Chaos Rune");
		Thread.sleep(500);
		Runecrafting.chaosRuneSiphon(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Runecrafting Siphon Astral Rune");
		Thread.sleep(500);
		Runecrafting.astralRuneSiphon(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Runecrafting Siphon Nature Rune");
		Thread.sleep(500);
		Runecrafting.natureRuneSiphon(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Runecrafting Siphon Law Rune");
		Thread.sleep(500);
		Runecrafting.lawRuneSiphon(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Runecrafting Siphon Death Rune");
		Thread.sleep(500);
		Runecrafting.deathRuneSiphon(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Runecrafting Siphon Blood Rune");
		Thread.sleep(500);
		Runecrafting.bloodRuneSiphon(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Runecrafting Siphon Soul Rune");
		Thread.sleep(500);
		Runecrafting.soulRuneSiphon(robot, yakTaskSelection);
		Thread.sleep(5000);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		
	}
	
		
	public static void yakSmeltingRun(Robot robot, String yakTaskSelection, String yakTaskQuantity) throws IOException, 
	AWTException, InterruptedException{
		
		Smelting.yakSmeltingTotal(robot, yakTaskQuantity);
		Thread.sleep(1000);
		Smelting.lumbridgeFurnace(robot);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Smelting Bronze Bar");
		Thread.sleep(500);
        Smelting.bronzeBar(robot, yakTaskSelection);
        Thread.sleep(5000);
        DebugProcs.setYakRecipe(robot, "Smelting Iron Bar");
		Thread.sleep(500);
        Smelting.ironBar(robot, yakTaskSelection);
        Thread.sleep(5000);
        DebugProcs.setYakRecipe(robot, "Smelting Steel Bar");
		Thread.sleep(500);
        Smelting.steelBar(robot, yakTaskSelection);
        Thread.sleep(5000);
        DebugProcs.setYakRecipe(robot, "Smelting Mithril Bar");
		Thread.sleep(500);
        Smelting.mithrilBar(robot, yakTaskSelection);
        Thread.sleep(5000);
        DebugProcs.setYakRecipe(robot, "Smelting Adamant Bar");
		Thread.sleep(500);
        Smelting.adamantBar(robot, yakTaskSelection);
        Thread.sleep(5000);
        DebugProcs.setYakRecipe(robot, "Smelting Runite Bar");
		Thread.sleep(500);
        Smelting.runiteBar(robot, yakTaskSelection);
        Thread.sleep(5000);
        DebugProcs.setYakRecipe(robot, "Smelting Orikalkum Bar");
		Thread.sleep(500);
        Smelting.orikalkumBar(robot, yakTaskSelection);
        Thread.sleep(5000);
        DebugProcs.setYakRecipe(robot, "Smelting Necronium Bar");
		Thread.sleep(500);
        Smelting.necroniumBar(robot, yakTaskSelection);
        Thread.sleep(5000);
        DebugProcs.setYakRecipe(robot, "Smelting Bane Bar");
		Thread.sleep(500);
        Smelting.baneBar(robot, yakTaskSelection);
        Thread.sleep(5000);
        DebugProcs.setYakRecipe(robot, "Smelting Elder Rune Bar");
		Thread.sleep(500);
        Smelting.elderRuneBar(robot, yakTaskSelection);
        Thread.sleep(5000);
        DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		
	}
	
	public static void yakSmithingRun(Robot robot, String yakTaskSelection, String yakTaskQuantity) throws IOException, 
	AWTException, InterruptedException{
		
		Smithing.yakSmithingTotal(robot, yakTaskQuantity);
		Thread.sleep(1000);
		Smithing.burthorpForge(robot);
		Thread.sleep(5000);
		DebugProcs.setYakRecipe(robot, "Smithing Bronze Full Helm");
		Thread.sleep(500);
		Smithing.bronzeSmithFullHelm(robot, yakTaskSelection);
		Thread.sleep(15000);
		DebugProcs.setYakRecipe(robot, "Smithing Bronze Med Helm");
		Thread.sleep(500);
		Smithing.bronzeSmithMedHelm(robot, yakTaskSelection);
		Thread.sleep(15000);
		DebugProcs.setYakRecipe(robot, "Smithing Bronze Platelegs");
		Thread.sleep(500);
		Smithing.bronzeSmithPlatelegs(robot, yakTaskSelection);
		Thread.sleep(22000);
		DebugProcs.setYakRecipe(robot, "Smithing Bronze Plateskirt");
		Thread.sleep(500);
		Smithing.bronzeSmithPlateskirt(robot, yakTaskSelection);
		Thread.sleep(22000);
		DebugProcs.setYakRecipe(robot, "Smithing Bronze Platebody");
		Thread.sleep(500);
		Smithing.bronzeSmithPlatebody(robot, yakTaskSelection);
		Thread.sleep(32000);
		DebugProcs.setYakRecipe(robot, "Smithing Bronze Chainbody");
		Thread.sleep(500);
		Smithing.bronzeSmithChainbody(robot, yakTaskSelection);
		Thread.sleep(32000);
		DebugProcs.setYakRecipe(robot, "Smithing Bronze Square Shield");
		Thread.sleep(500);
		Smithing.bronzeSmithSquareShield(robot, yakTaskSelection);
		Thread.sleep(18000);
		DebugProcs.setYakRecipe(robot, "Smithing Bronze Kiteshield");
		Thread.sleep(500);
		Smithing.bronzeSmithKiteshield(robot, yakTaskSelection);
		Thread.sleep(18000);
		DebugProcs.setYakRecipe(robot, "Smithing Bronze Armoured Boots");
		Thread.sleep(500);
		Smithing.bronzeSmithArmouredBoots(robot, yakTaskSelection);
		Thread.sleep(10000);
		DebugProcs.setYakRecipe(robot, "Smithing Bronze Gauntlets");
		Thread.sleep(500);
		Smithing.bronzeSmithGauntlets(robot, yakTaskSelection);
		Thread.sleep(10000);
		DebugProcs.setYakRecipe(robot, "Smithing Iron Full Helm");
		Thread.sleep(500);
		Smithing.ironSmithFullHelm(robot, yakTaskSelection);
		Thread.sleep(30000);
		DebugProcs.setYakRecipe(robot, "Smithing Iron Med Helm");
		Thread.sleep(500);
		Smithing.ironSmithMedHelm(robot, yakTaskSelection);
		Thread.sleep(30000);
		DebugProcs.setYakRecipe(robot, "Smithing Iron Platelegs");
		Thread.sleep(500);
		Smithing.ironSmithPlatelegs(robot, yakTaskSelection);
		Thread.sleep(40000);
		DebugProcs.setYakRecipe(robot, "Smithing Iron Plateskirt");
		Thread.sleep(500);
		Smithing.ironSmithPlateskirt(robot, yakTaskSelection);
		Thread.sleep(40000);
		DebugProcs.setYakRecipe(robot, "Smithing Iron Platebody");
		Thread.sleep(500);
		Smithing.ironSmithPlatebody(robot, yakTaskSelection);
		Thread.sleep(50000);
		DebugProcs.setYakRecipe(robot, "Smithing Iron Chainbody");
		Thread.sleep(500);
		Smithing.ironSmithChainbody(robot, yakTaskSelection);
		Thread.sleep(50000);
		DebugProcs.setYakRecipe(robot, "Smithing Iron Square Shield");
		Thread.sleep(500);
		Smithing.ironSmithSquareShield(robot, yakTaskSelection);
		Thread.sleep(30000);
		DebugProcs.setYakRecipe(robot, "Smithing Iron Kiteshield");
		Thread.sleep(500);
		Smithing.ironSmithKiteshield(robot, yakTaskSelection);
		Thread.sleep(30000);
		DebugProcs.setYakRecipe(robot, "Smithing Iron Armoured Boots");
		Thread.sleep(500);
		Smithing.ironSmithArmouredBoots(robot, yakTaskSelection);
		Thread.sleep(25000);
		DebugProcs.setYakRecipe(robot, "Smithing Iron Gauntlets");
		Thread.sleep(500);
		Smithing.ironSmithGauntlets(robot, yakTaskSelection);
		Thread.sleep(25000);
		DebugProcs.setYakRecipe(robot, "Smithing steel Full Helm");
		Thread.sleep(500);
		Smithing.steelSmithFullHelm(robot, yakTaskSelection);
		Thread.sleep(40000);
		DebugProcs.setYakRecipe(robot, "Smithing steel Med Helm");
		Thread.sleep(500);
		Smithing.steelSmithMedHelm(robot, yakTaskSelection);
		Thread.sleep(40000);
		DebugProcs.setYakRecipe(robot, "Smithing steel Platelegs");
		Thread.sleep(500);
		Smithing.steelSmithPlatelegs(robot, yakTaskSelection);
		Thread.sleep(56000);
		DebugProcs.setYakRecipe(robot, "Smithing steel Plateskirt");
		Thread.sleep(500);
		Smithing.steelSmithPlateskirt(robot, yakTaskSelection);
		Thread.sleep(56000);
		DebugProcs.setYakRecipe(robot, "Smithing steel Platebody");
		Thread.sleep(500);
		Smithing.steelSmithPlatebody(robot, yakTaskSelection);
		Thread.sleep(107000);
		DebugProcs.setYakRecipe(robot, "Smithing steel Chainbody");
		Thread.sleep(500);
		Smithing.steelSmithChainbody(robot, yakTaskSelection);
		Thread.sleep(107000);
		DebugProcs.setYakRecipe(robot, "Smithing steel Square Shield");
		Thread.sleep(500);
		Smithing.steelSmithSquareShield(robot, yakTaskSelection);
		Thread.sleep(37000);
		DebugProcs.setYakRecipe(robot, "Smithing steel Kiteshield");
		Thread.sleep(500);
		Smithing.steelSmithKiteshield(robot, yakTaskSelection);
		Thread.sleep(37000);
		DebugProcs.setYakRecipe(robot, "Smithing steel Armoured Boots");
		Thread.sleep(500);
		Smithing.steelSmithArmouredBoots(robot, yakTaskSelection);
		Thread.sleep(30000);
		DebugProcs.setYakRecipe(robot, "Smithing steel Gauntlets");
		Thread.sleep(500);
		Smithing.steelSmithGauntlest(robot, yakTaskSelection);
		Thread.sleep(30000);
		DebugProcs.setYakRecipe(robot, "Smithing mithril Full Helm");
		Thread.sleep(500);
		Smithing.mithrilSmithFullHelm(robot, yakTaskSelection);
		Thread.sleep(50000);
		DebugProcs.setYakRecipe(robot, "Smithing mithril Med Helm");
		Thread.sleep(500);
		Smithing.mithrilSmithMedHelm(robot, yakTaskSelection);
		Thread.sleep(50000);
		DebugProcs.setYakRecipe(robot, "Smithing mithril Platelegs");
		Thread.sleep(500);
		Smithing.mithrilSmithPlatelegs(robot, yakTaskSelection);
		Thread.sleep(79000);
		DebugProcs.setYakRecipe(robot, "Smithing mithril Plateskirt");
		Thread.sleep(500);
		Smithing.mithrilSmithPlateskirt(robot, yakTaskSelection);
		Thread.sleep(79000);
		DebugProcs.setYakRecipe(robot, "Smithing mithril Platebody");
		Thread.sleep(500);
		Smithing.mithrilSmithPlatebody(robot, yakTaskSelection);
		Thread.sleep(40000);
		DebugProcs.setYakRecipe(robot, "Smithing mithril Chainbody");
		Thread.sleep(500);
		Smithing.mithrilSmithChainbody(robot, yakTaskSelection);
		Thread.sleep(40000);
		DebugProcs.setYakRecipe(robot, "Smithing mithril Square Shield");
		Thread.sleep(500);
		Smithing.mithrilSmithSquareShield(robot, yakTaskSelection);
		Thread.sleep(47000);
		DebugProcs.setYakRecipe(robot, "Smithing mithril Kiteshield");
		Thread.sleep(500);
		Smithing.mithrilSmithKiteshield(robot, yakTaskSelection);
		Thread.sleep(47000);
		DebugProcs.setYakRecipe(robot, "Smithing mithril Armoured Boots");
		Thread.sleep(500);
		Smithing.mithrilSmithArmouredBoots(robot, yakTaskSelection);
		Thread.sleep(30000);
		DebugProcs.setYakRecipe(robot, "Smithing mithril Gauntlets");
		Thread.sleep(500);
		Smithing.mithrilSmithGauntlets(robot, yakTaskSelection);
		Thread.sleep(30000);
		DebugProcs.setYakRecipe(robot, "Smithing adamantite Full Helm");
		Thread.sleep(500);
		Smithing.adamantSmithFullHelm(robot, yakTaskSelection);
		Thread.sleep(65000);
		DebugProcs.setYakRecipe(robot, "Smithing adamantite Med Helm");
		Thread.sleep(500);
		Smithing.adamantSmithMedHelm(robot, yakTaskSelection);
		Thread.sleep(65000);
		DebugProcs.setYakRecipe(robot, "Smithing adamantite Platelegs");
		Thread.sleep(500);
		Smithing.adamantSmithPlatelegs(robot, yakTaskSelection);
		Thread.sleep(110000);
		DebugProcs.setYakRecipe(robot, "Smithing adamantite Plateskirt");
		Thread.sleep(500);
		Smithing.adamantSmithPlateskirt(robot, yakTaskSelection);
		Thread.sleep(110000);
		DebugProcs.setYakRecipe(robot, "Smithing adamantite Platebody");
		Thread.sleep(500);
		Smithing.adamantSmithPlatebody(robot, yakTaskSelection);
		Thread.sleep(70000);
		DebugProcs.setYakRecipe(robot, "Smithing adamantite Chainbody");
		Thread.sleep(500);
		Smithing.adamantSmithChainbody(robot, yakTaskSelection);
		Thread.sleep(70000);
		DebugProcs.setYakRecipe(robot, "Smithing adamantite Square Shield");
		Thread.sleep(500);
		Smithing.adamantSmithSquareShield(robot, yakTaskSelection);
		Thread.sleep(67000);
		DebugProcs.setYakRecipe(robot, "Smithing adamantite Kiteshield");
		Thread.sleep(500);
		Smithing.adamantSmithKiteshield(robot, yakTaskSelection);
		Thread.sleep(67000);
		DebugProcs.setYakRecipe(robot, "Smithing adamantite Armoured Boots");
		Thread.sleep(500);
		Smithing.adamantSmithArmouredBoots(robot, yakTaskSelection);
		Thread.sleep(35000);
		DebugProcs.setYakRecipe(robot, "Smithing adamantite Gauntlets");
		Thread.sleep(500);
		Smithing.adamantSmithGauntlets(robot, yakTaskSelection);
		Thread.sleep(35000);
		DebugProcs.setYakRecipe(robot, "Smithing runite Full Helm");
		Thread.sleep(500);
		Smithing.runiteSmithFullHelm(robot, yakTaskSelection);
		Thread.sleep(80000);
		DebugProcs.setYakRecipe(robot, "Smithing runite Med Helm");
		Thread.sleep(500);
		Smithing.runiteSmithMedHelm(robot, yakTaskSelection);
		Thread.sleep(80000);
		DebugProcs.setYakRecipe(robot, "Smithing runite Platelegs");
		Thread.sleep(500);
		Smithing.runiteSmithPlatelegs(robot, yakTaskSelection);
		Thread.sleep(40000);
		DebugProcs.setYakRecipe(robot, "Smithing runite Plateskirt");
		Thread.sleep(500);
		Smithing.runiteSmithPlateskirt(robot, yakTaskSelection);
		Thread.sleep(40000);
		DebugProcs.setYakRecipe(robot, "Smithing runite Platebody");
		Thread.sleep(500);
		Smithing.runiteSmithPlatebody(robot, yakTaskSelection);
		Thread.sleep(30000);
		DebugProcs.setYakRecipe(robot, "Smithing runite Chainbody");
		Thread.sleep(500);
		Smithing.runiteSmithChainbody(robot, yakTaskSelection);
		Thread.sleep(30000);
		DebugProcs.setYakRecipe(robot, "Smithing runite Square Shield");
		Thread.sleep(500);
		Smithing.runiteSmithSquareShield(robot, yakTaskSelection);
		Thread.sleep(82000);
		DebugProcs.setYakRecipe(robot, "Smithing runite Kiteshield");
		Thread.sleep(500);
		Smithing.runiteSmithKiteshield(robot, yakTaskSelection);
		Thread.sleep(82000);
		DebugProcs.setYakRecipe(robot, "Smithing runite Armoured Boots");
		Thread.sleep(500);
		Smithing.runiteSmithArmouredBoots(robot, yakTaskSelection);
		Thread.sleep(40000);
		DebugProcs.setYakRecipe(robot, "Smithing runite Gauntlets");
		Thread.sleep(500);
		Smithing.runiteSmithGauntlets(robot, yakTaskSelection);
		Thread.sleep(40000);
		DebugProcs.setYakRecipe(robot, "Smithing orikalkum Full Helm");
		Thread.sleep(500);
		Smithing.orikalkumSmithFullHelm(robot, yakTaskSelection);
		Thread.sleep(100000);
		DebugProcs.setYakRecipe(robot, "Smithing orikalkum Platelegs");
		Thread.sleep(500);
		Smithing.orikalkumSmithPlatelegs(robot, yakTaskSelection);
		Thread.sleep(40000);
		DebugProcs.setYakRecipe(robot, "Smithing orikalkum Platebody");
		Thread.sleep(500);
		Smithing.orikalkumSmithPlatebody(robot, yakTaskSelection);
		Thread.sleep(50000);
		DebugProcs.setYakRecipe(robot, "Smithing orikalkum Kiteshield");
		Thread.sleep(500);
		Smithing.orikalkumSmithKiteshield(robot, yakTaskSelection);
		Thread.sleep(90000);
		DebugProcs.setYakRecipe(robot, "Smithing orikalkum Armoured Boots");
		Thread.sleep(500);
		Smithing.orikalkumSmithArmouredBoots(robot, yakTaskSelection);
		Thread.sleep(50000);
		DebugProcs.setYakRecipe(robot, "Smithing orikalkum Gauntlets");
		Thread.sleep(500);
		Smithing.orikalkumSmithGauntlets(robot, yakTaskSelection);
		Thread.sleep(50000);
		DebugProcs.setYakRecipe(robot, "Smithing necronium Full Helm");
		Thread.sleep(500);
		Smithing.necroniumSmithFullHelm(robot, yakTaskSelection);
		Thread.sleep(140000);
		DebugProcs.setYakRecipe(robot, "Smithing necronium Platelegs");
		Thread.sleep(500);
		Smithing.necroniumSmithPlatelegs(robot, yakTaskSelection);
		Thread.sleep(70000);
		DebugProcs.setYakRecipe(robot, "Smithing necronium Platebody");
		Thread.sleep(500);
		Smithing.necroniumSmithPlatebody(robot, yakTaskSelection);
		Thread.sleep(60000);
		DebugProcs.setYakRecipe(robot, "Smithing necronium Kiteshield");
		Thread.sleep(500);
		Smithing.necroniumSmithKiteshield(robot, yakTaskSelection);
		Thread.sleep(120000);
		DebugProcs.setYakRecipe(robot, "Smithing necronium Armoured Boots");
		Thread.sleep(500);
		Smithing.necroniumSmithArmouredBoots(robot, yakTaskSelection);
		Thread.sleep(60000);
		DebugProcs.setYakRecipe(robot, "Smithing necronium Gauntlets");
		Thread.sleep(500);
		Smithing.necroniumSmithGauntlets(robot, yakTaskSelection);
		Thread.sleep(60000);
		DebugProcs.setYakRecipe(robot, "Smithing bane Full Helm");
		Thread.sleep(500);
		Smithing.baneSmithFullHelm(robot, yakTaskSelection);
		Thread.sleep(140000);
		DebugProcs.setYakRecipe(robot, "Smithing bane Platelegs");
		Thread.sleep(500);
		Smithing.baneSmithPlatelegs(robot, yakTaskSelection);
		Thread.sleep(80000);
		DebugProcs.setYakRecipe(robot, "Smithing bane Platebody");
		Thread.sleep(500);
		Smithing.baneSmithPlatebody(robot, yakTaskSelection);
		Thread.sleep(60000);
		DebugProcs.setYakRecipe(robot, "Smithing bane Kiteshield");
		Thread.sleep(500);
		Smithing.baneSmithKiteshield(robot, yakTaskSelection);
		Thread.sleep(140000);
		DebugProcs.setYakRecipe(robot, "Smithing bane Armoured Boots");
		Thread.sleep(500);
		Smithing.baneSmithArmouredBoots(robot, yakTaskSelection);
		Thread.sleep(80000);
		DebugProcs.setYakRecipe(robot, "Smithing bane Gauntlets");
		Thread.sleep(500);
		Smithing.baneSmithGauntlets(robot, yakTaskSelection);
		Thread.sleep(80000);
		DebugProcs.setYakRecipe(robot, "Smithing elder_rune Full Helm");
		Thread.sleep(500);
		Smithing.elderRuneSmithFullHelm(robot, yakTaskSelection);
		Thread.sleep(160000);
		DebugProcs.setYakRecipe(robot, "Yak Task = Smithing elder_rune Platelegs");
		Thread.sleep(500);
		Smithing.elderRuneSmithPlatelegs(robot, yakTaskSelection);
		Thread.sleep(120000);
		DebugProcs.setYakRecipe(robot, "Smithing elder_rune Platebody");
		Thread.sleep(500);
		Smithing.elderRuneSmithPlatebody(robot, yakTaskSelection);
		Thread.sleep(60000);
		DebugProcs.setYakRecipe(robot, "Smithing elder_rune Round Shield");
		Thread.sleep(500);
		Smithing.elderRuneSmithKiteshield(robot, yakTaskSelection);
		Thread.sleep(130000);
		DebugProcs.setYakRecipe(robot, "Smithing elder_rune Armoured Boots");
		Thread.sleep(500);
		Smithing.elderRuneSmithArmouredBoots(robot, yakTaskSelection);
		Thread.sleep(80000);
		DebugProcs.setYakRecipe(robot, "Smithing elder_rune Gauntlets");
		Thread.sleep(500);
		Smithing.elderRuneSmithGauntlets(robot, yakTaskSelection);
		Thread.sleep(80000);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		
		
	}
	
	public static void yakSummoningRun(Robot robot, String yakTaskSelection, String yakTaskQuantity) throws IOException, 
	AWTException, InterruptedException{
		
		Summoning.yakSummoningTotal(robot, yakTaskQuantity);
		Thread.sleep(1000);
		Summoning.summoningObeliskAccess(robot);
		Thread.sleep(10000);
		DebugProcs.setYakRecipe(robot, "Summoning Spirit Wolf");
		Thread.sleep(500);
		Summoning.spiritWolf(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Dreadfowl");
		Thread.sleep(500);
		Summoning.dreadfowl(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Spirit Spider");
		Thread.sleep(500);
		Summoning.spiritSpider(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Thorny Snail");
		Thread.sleep(500);
		Summoning.thornySnail(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Granite Crab");
		Thread.sleep(500);
		Summoning.graniteCrab(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Spirit Mosquito");
		Thread.sleep(500);
		Summoning.spiritMosquito(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Desert Wyrm");
		Thread.sleep(500);
		Summoning.desertWyrm(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Spirit Scorpion");
		Thread.sleep(500);
		Summoning.spiritScorpion(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Spirit Tzkih");
		Thread.sleep(500);
		Summoning.spiritTzKih(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Albino Rat");
		Thread.sleep(500);
		Summoning.albinoRat(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Spirit Kaliphite");
		Thread.sleep(500);
		Summoning.spiritKalphite(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Compost Mound");
		Thread.sleep(500);
		Summoning.compostMound(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Giant Chinchompa");
		Thread.sleep(500);
		Summoning.giantChinchompa(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Vampyr Bat");
		Thread.sleep(500);
		Summoning.vampyrBat(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Honey Badger");
		Thread.sleep(500);
		Summoning.honeyBadger(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Beaver");
		Thread.sleep(500);
		Summoning.beaver(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Void Ravager");
		Thread.sleep(500);
		Summoning.voidRavager(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Void Shifter");
		Thread.sleep(500);
		Summoning.voidShifter(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Void Spinner");
		Thread.sleep(500);
		Summoning.voidSpinner(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Void Torcher");
		Thread.sleep(500);
		Summoning.voidTorcher(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Bronze Minotaur");
		Thread.sleep(500);
		Summoning.bronzeMinotaur(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Bull Ant");
		Thread.sleep(500);
		Summoning.bullAnt(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Macaw");
		Thread.sleep(500);
		Summoning.macaw(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Evil Turnip");
		Thread.sleep(500);
		Summoning.evilTurnip(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Spirit Cockatrice");
		Thread.sleep(500);
		Summoning.spiritCockatrice(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Spirit Guthatrice");
		Thread.sleep(500);
		Summoning.spiritGuthatrice(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Spirit Saratrice");
		Thread.sleep(500);
		Summoning.spiritSaratrice(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Spirit Zamatrice");
		Thread.sleep(500);
		Summoning.spiritZamatrice(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Spirit Pengatrice");
		Thread.sleep(500);
		Summoning.spiritPengatrice(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Spirit Coraxatrice");
		Thread.sleep(500);
		Summoning.spiritCoraxatrice(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Spirit Vulatrice");
		Thread.sleep(500);
		Summoning.spiritVulatrice(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Iron Minotaur");
		Thread.sleep(500);
		Summoning.ironMinotaur(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Pyrelord");
		Thread.sleep(500);
		Summoning.pyrelord(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Magpie");
		Thread.sleep(500);
		Summoning.magpie(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Bloated Leech");
		Thread.sleep(500);
		Summoning.bloatedLeech(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Spirit Terrorbird");
		Thread.sleep(500);
		Summoning.spiritTerrobird(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Abyssal Parasite");
		Thread.sleep(500);
		Summoning.abyssalParasite(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Spirit Jelly");
		Thread.sleep(500);
		Summoning.spiritJelly(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Ibis");
		Thread.sleep(500);
		Summoning.ibis(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Steel Minotaur");
		Thread.sleep(500);
		Summoning.steelMinotaur(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Spirit Graahk");
		Thread.sleep(500);
		Summoning.spiritGraahk(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Spirit Kyatt");
		Thread.sleep(500);
		Summoning.spiritKyatt(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Spirit Larupia");
		Thread.sleep(500);
		Summoning.spiritLarupia(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Karam");
		Thread.sleep(500);
		Summoning.karam(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Smoke Devil");
		Thread.sleep(500);
		Summoning.smokeDevil(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Abyssal Lurker");
		Thread.sleep(500);
		Summoning.abyssalLurker(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Spirit Cobra");
		Thread.sleep(500);
		Summoning.spiritCobra(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Stranger Plant");
		Thread.sleep(500);
		Summoning.strangerPlant(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Barker Toad");
		Thread.sleep(500);
		Summoning.barkerToad(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Mithril Minotaur");
		Thread.sleep(500);
		Summoning.mithrilMinotaur(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning War Tortoise");
		Thread.sleep(500);
		Summoning.warTortoise(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Bunyip");
		Thread.sleep(500);
		Summoning.bunyip(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Fruit Bat");
		Thread.sleep(500);
		Summoning.fruitBat(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Ravenous Locust");
		Thread.sleep(500);
		Summoning.ravenousLocust(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Arctic Bear");
		Thread.sleep(500);
		Summoning.arcticBear(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Phoenix");
		Thread.sleep(500);
		Summoning.phoenix(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Obsidian Golem");
		Thread.sleep(500);
		Summoning.obsidianGolem(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Granite Lobster");
		Thread.sleep(500);
		Summoning.graniteLobster(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Praying Mantis");
		Thread.sleep(500);
		Summoning.prayingMantis(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Forge Regent");
		Thread.sleep(500);
		Summoning.forgeRegent(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Adamant Minotaur");
		Thread.sleep(500);
		Summoning.adamantMinotaur(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Talon Beast");
		Thread.sleep(500);
		Summoning.talonBeast(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Giant Ent");
		Thread.sleep(500);
		Summoning.giantEnt(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Fire Titan");
		Thread.sleep(500);
		Summoning.fireTitan(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Moss Titan");
		Thread.sleep(500);
		Summoning.mossTitan(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Ice Titan");
		Thread.sleep(500);
		Summoning.iceTitan(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Hydra");
		Thread.sleep(500);
		Summoning.hydra(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Brawler Demon");
		Thread.sleep(500);
		Summoning.demonBrawler(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Deacon Demon");
		Thread.sleep(500);
		Summoning.demonDeacon(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Excutioner Demon");
		Thread.sleep(500);
		Summoning.demonExecutioner(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Spirit Dagannoth");
		Thread.sleep(500);
		Summoning.spiritDagannoth(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Lava Titan");
		Thread.sleep(500);
		Summoning.lavaTitan(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Reborn Phoenix");
		Thread.sleep(500);
		Summoning.rebornPhoenix(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Swamp Titan");
		Thread.sleep(500);
		Summoning.swampTitan(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Rune Minotaur");
		Thread.sleep(500);
		Summoning.runeMinotaur(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Unicorn Stallion");
		Thread.sleep(500);
		Summoning.unicornStallion(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Light Creature");
		Thread.sleep(500);
		Summoning.lightCreature(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Geyser Titan");
		Thread.sleep(500);
		Summoning.geyserTitan(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Wolpertinger");
		Thread.sleep(500);
		Summoning.wolpertinger(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Abyssal Titan");
		Thread.sleep(500);
		Summoning.abyssalTitan(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Iron Titan");
		Thread.sleep(500);
		Summoning.ironTitan(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Pak Yak");
		Thread.sleep(500);
		Summoning.pakYak(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Pack Mammoth");
		Thread.sleep(500);
		Summoning.packMammoth(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.setYakRecipe(robot, "Summoning Steel Titan");
		Thread.sleep(500);
		Summoning.steelTitan(robot, yakTaskSelection);
		Thread.sleep(6000);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		
	}
	
	public static void yakThievingRun(Robot robot, String yakTaskSelection, String yakTaskQuantity) throws IOException, 
	AWTException, InterruptedException{
		
		Thieving.yakThievingTotal(robot, yakTaskQuantity);
		Thread.sleep(3000);
		DebugProcs.setYakRecipe(robot, "Thieving Man");
		Thread.sleep(500);
		Thieving.man(robot, yakTaskSelection);
		Thread.sleep(3000);
		DebugProcs.setYakRecipe(robot, "Thieving Woman");
		Thread.sleep(500);
		Thieving.woman(robot, yakTaskSelection);
		Thread.sleep(3000);
		DebugProcs.setYakRecipe(robot, "Thieving Farmer");
		Thread.sleep(500);
		Thieving.farmer(robot, yakTaskSelection);
		Thread.sleep(3000);
		DebugProcs.setYakRecipe(robot, "Thieving Female H.A.M Member");
		Thread.sleep(500);
		Thieving.femaleHAM(robot, yakTaskSelection);
		Thread.sleep(3000);
		DebugProcs.setYakRecipe(robot, "Thieving Male H.A.M Member");
		Thread.sleep(500);
		Thieving.maleHAM(robot, yakTaskSelection);
		Thread.sleep(3000);
		DebugProcs.setYakRecipe(robot, "Thieving H.A.M Guard");
		Thread.sleep(500);
		Thieving.hamGuard(robot, yakTaskSelection);
		Thread.sleep(3000);
		DebugProcs.setYakRecipe(robot, "Thieving Warrior");
		Thread.sleep(500);
		Thieving.warrior(robot, yakTaskSelection);
		Thread.sleep(3000);
		DebugProcs.setYakRecipe(robot, "Thieving Rogue");
		Thread.sleep(500);
		Thieving.rogue(robot, yakTaskSelection);
		Thread.sleep(3000);
		DebugProcs.setYakRecipe(robot, "Thieving Cave Goblin");
		Thread.sleep(500);
		Thieving.caveGoblin(robot, yakTaskSelection);
		Thread.sleep(3000);
		DebugProcs.setYakRecipe(robot, "Thieving Master Farmer");
		Thread.sleep(500);
		Thieving.masterFarmer(robot, yakTaskSelection);
		Thread.sleep(3000);
		DebugProcs.setYakRecipe(robot, "Thieving Guard");
		Thread.sleep(500);
		Thieving.guard(robot, yakTaskSelection);
		Thread.sleep(3000);
		DebugProcs.setYakRecipe(robot, "Thieving Fremennik Citizen");
		Thread.sleep(500);
		Thieving.fremennikCitizen(robot, yakTaskSelection);
		Thread.sleep(3000);
		DebugProcs.setYakRecipe(robot, "Thieving Bearded Pollnivnian Bandits");
		Thread.sleep(500);
		Thieving.pollnivnianBandit(robot, yakTaskSelection);
		Thread.sleep(3000);
		DebugProcs.setYakRecipe(robot, "Thieving Desert Bandits");
		Thread.sleep(500);
		Thieving.desertBandit(robot, yakTaskSelection);
		Thread.sleep(3000);
		DebugProcs.setYakRecipe(robot, "Thieving Ardougne Knight");
		Thread.sleep(500);
		Thieving.ardougneKnight(robot, yakTaskSelection);
		Thread.sleep(3000);
		DebugProcs.setYakRecipe(robot, "Thieving Pollnivnian Bandit");
		Thread.sleep(500);
		Thieving.pollnivnianBandit2(robot, yakTaskSelection);
		Thread.sleep(3000);
		DebugProcs.setYakRecipe(robot, "Thieving Yanille Watchman");
		Thread.sleep(500);
		Thieving.yanilleWatchman(robot, yakTaskSelection);
		Thread.sleep(3000);
		DebugProcs.setYakRecipe(robot, "Thieving Menaphite Thug");
		Thread.sleep(500);
		Thieving.thug(robot, yakTaskSelection);
		Thread.sleep(3000);
		DebugProcs.setYakRecipe(robot, "Thieving Paladin");
		Thread.sleep(500);
		Thieving.paladin(robot, yakTaskSelection);
		Thread.sleep(3000);
		DebugProcs.setYakRecipe(robot, "Thieving Gnome");
		Thread.sleep(500);
		Thieving.gnome(robot, yakTaskSelection);
		Thread.sleep(3000);
		DebugProcs.setYakRecipe(robot, "Thieving Hero");
		Thread.sleep(500);
		Thieving.hero(robot, yakTaskSelection);
		Thread.sleep(3000);
		DebugProcs.setYakRecipe(robot, "Thieving Elves");
		Thread.sleep(500);
		Thieving.elves(robot, yakTaskSelection);
		Thread.sleep(3000);
		DebugProcs.setYakRecipe(robot, "Thieving Dwarf Trader");
		Thread.sleep(500);
		Thieving.dwarfTrader(robot, yakTaskSelection);
		Thread.sleep(3000);
		DebugProcs.setYakRecipe(robot, "Thieving Iowerth Worker");
		Thread.sleep(500);
		Thieving.iowerthWorker(robot, yakTaskSelection);
		Thread.sleep(3000);
		DebugProcs.setYakRecipe(robot, "Thieving Ithell Worker");
		Thread.sleep(500);
		Thieving.ithellWorker(robot, yakTaskSelection);
		Thread.sleep(3000);
		DebugProcs.setYakRecipe(robot, "Thieving Cadarn Worker");
		Thread.sleep(500);
		Thieving.cadarnWorker(robot, yakTaskSelection);
		Thread.sleep(3000);
		DebugProcs.setYakRecipe(robot, "Thieving Amlodd Worker");
		Thread.sleep(500);
		Thieving.amloddWorker(robot, yakTaskSelection);
		Thread.sleep(3000);
		DebugProcs.setYakRecipe(robot, "Thieving Trahaearn Worker");
		Thread.sleep(500);
		Thieving.trahaernWorker(robot, yakTaskSelection);
		Thread.sleep(3000);
		DebugProcs.setYakRecipe(robot, "Thieving Hefin Worker");
		Thread.sleep(500);
		Thieving.hefinWorker(robot, yakTaskSelection);
		Thread.sleep(3000);
		DebugProcs.setYakRecipe(robot, "Thieving Crwys Worker");
		Thread.sleep(500);
		Thieving.crwysWorker(robot, yakTaskSelection);
		Thread.sleep(3000);
		DebugProcs.setYakRecipe(robot, "Thieving Meilyr Worker");
		Thread.sleep(500);
		Thieving.meilyrWorker(robot, yakTaskSelection);
		Thread.sleep(3000);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);	
		
	}
	
	public static void yakWoodCuttingRun(Robot robot, String yakTaskSelection, String yakTaskQuantity) throws IOException, 
	AWTException, InterruptedException{

		DebugProcs.setNPCAttack(robot);
		Thread.sleep(5000);
		WoodCutting.yakWoodcuttingTotal(robot, yakTaskQuantity);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Woodcutting Logs");
		Thread.sleep(500);
		WoodCutting.normalLogs(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Woodcutting Oak");
		Thread.sleep(500);
		WoodCutting.oakLogs(robot,yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Woodcutting Willow");
		Thread.sleep(500);
		WoodCutting.willowLogs(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Woodcutting Teak");
		Thread.sleep(500);
		WoodCutting.teakLogs(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Woodcutting Maple");
		Thread.sleep(500);
		WoodCutting.mapleLogs(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Woodcutting Acadia");
		Thread.sleep(500);
		WoodCutting.acadiaLogs(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Woodcutting Mahogany");
		Thread.sleep(500);
		WoodCutting.mahoganyLogs(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Woodcutting Arctic Pine");
		Thread.sleep(500);
		WoodCutting.pineLogs(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Woodcutting Eucalyptus");
		Thread.sleep(500);
		WoodCutting.eucalyptusLogs(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Woodcutting Yew");
		Thread.sleep(500);
		WoodCutting.yewLogs(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Woodcutting Magic Logs");
		Thread.sleep(500);
		WoodCutting.magicLogs(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Woodcutting Elder Logs");
		Thread.sleep(500);
		WoodCutting.elderLogs(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.setYakRecipe(robot, "Woodcutting Bamboo");
		Thread.sleep(500);
		WoodCutting.bambooLogs(robot, yakTaskSelection);
		Thread.sleep(500);
		DebugProcs.yakTaskProgress(robot, yakTaskSelection);
		
	}

}
